### ISSUE TITLE
Support for Miktex > 2019: ! Extra \endgroup.   \error in 

### ISSUE THREAD

**Issue by 4db83** [blumu/latexdaemon#37]
Hi William, I have been using LatexDaemon since 2007 and, first of all, should thank you for creating it. :).  

With updates to Miktex, however, it seems to throw this error how that I cannot resolve (On a 2019 version of miktex it does not)

! Extra \endgroup.
  \document ->\endgroup
                        \immediate \closeout \preambledepfile \let \input \DAE...
  l.5 \begin{document}

The latex file is a simple "hello world": ie. 

\documentclass[12pt]{article}
\begin{document}
\title{LatexDaemon Error Message}
\author{Me}
\maketitle
\section{Test}
Hello world
\end{document}

Full error log output is in the "Output Snapshot.png" file for you to see, also showing the miktex version MiKTeX-TeX 4.3 (MiKTeX 21.8). 

Could you, may be, help me find out what the problem is to fix it?

Thank you so much. 
![Output Snapshot](https://user-images.githubusercontent.com/84711454/134661159-cdefb804-32ce-488c-840e-2742e1411dde.png)

**Comment by blumu** [comment]
@4db83 You are very welcome, glad that LaTeXDaemon has been working fine for you all these years! It's unfortunate that it stopped working recently. Thanks for reporting the issue. This does look like a breaking change in MikTeX. I wonder if it would make sense to report it at https://github.com/MiKTeX/miktex/issues

Have you tried the [latest version 21.12](https://github.com/MiKTeX/miktex/releases?after=2.9.7445) to see if the problem got fixed by any chance?

**Comment by 4db83** [comment]
Hi William, wow that is a fast reply. I did not expect that. 

 

I will try the latest version tomorrow (it’s late in Stockholm now). 

 

If that still throws the same errors, I will do as you suggest to report to miktex. I have been trying to find the something like “\immediate \closeout \preambledepfile \let” in LatexDaemon source code, but I could not. I will try to do a search in the Miktex source code also, but I am not a programmer by training, so could be a very clumsy attempt. 

 

Thanks again, it has been working fantastic. 

 

Best wishes

 

Daniel

**Comment by blumu** [comment]
There is a workaround by just removing the `\\endgroup`` command at:

https://github.com/blumu/latexdaemon/blob/5dc099e2af172548d75d26758bf9c6d6eaa18248/latexdaemon/main.cpp#L2309


I verified that it works on MikTeX 21.12 though I assume it would break previous version of MikTex.

**Comment by blumu** [comment]
@4db83 There were a fix recently checked-in in the `mylatex` package, I cherry-picked the change into latexdaemon and it seems to fix the problem. You can try a private build at https://github.com/blumu/latexdaemon/suites/4720667365/artifacts/129796366

**Comment by blumu** [comment]
Fixed in #39
